version: '3.3'

services:
  app:
    build:
      context: .
    volumes:
       - ./notebooks:/opt/notebooks
       - .:/app
    ports:
      - "3000:3000"
    command:
      /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=3000 --no-browser --allow-root
    tty: true
